apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-jenkins-nexus-qa-040325 
  description: Secure Supply Chain Example for C# .Net 6.0 example with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=dotnet-jenkins-nexus-qa-040325
    backstage.io/kubernetes-id: dotnet-jenkins-nexus-qa-040325 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: dotnet-jenkins-nexus-qa-040325
    nexus-repository-manager/docker.image-name: rhtap/nexus-ga
  tags: ["net", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 